### ISSUE TITLE
Unable to assing keyvault Access Policy to function app identity

### ISSUE THREAD

**Issue by StefanSchoof** [pulumi/pulumi-azure#192]
I try to set up a azure function with a managed identity to get permission to access a keyvault.

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as azure from "@pulumi/azure";

const current = pulumi.output(azure.core.getClientConfig({}));

const resourceGroup = new azure.core.ResourceGroup("resourceGroup", {
    location: "WestUS",
});

const plan = new azure.appservice.Plan("plan", {
    kind: "functionapp",
    location: resourceGroup.location,
    name: "plan",
    resourceGroupName: resourceGroup.name,
    sku: {
        size: "Y1",
        tier: "Dynamic",
    },
});

const storage = new azure.storage.Account("storage", {
    accountKind: "StorageV2",
    accountReplicationType: "LRS",
    accountTier: "Standard",
    location: resourceGroup.location,
    name: "storage",
    resourceGroupName: resourceGroup.name,
});

const functionApp = new azure.appservice.FunctionApp("function", {
    appServicePlanId: plan.id,
    identity: {
        type: "SystemAssigned",
    },
    location: resourceGroup.location,
    name: "function",
    resourceGroupName: resourceGroup.name,
    storageConnectionString: storage.primaryConnectionString,
    version: "~2",
});
const keyvault = new azure.keyvault.KeyVault("keyvault", {
    location: resourceGroup.location,
    name: "keyvault",
    resourceGroupName: resourceGroup.name,
    sku: {
        name: "standard",
    },
    tenantId: current.apply(current => current.tenantId),
});

const app = new azure.keyvault.AccessPolicy("app", {
    keyPermissions: [],
    keyVaultId: keyvault.id,
    objectId: functionApp.identity.apply(identity => identity.principalId),
    secretPermissions: ["get"],
    tenantId: functionApp.identity.apply(identity => identity.tenantId),
});

```

this script results in following error:

```
$ pulumi up
Previewing update (dev3):

     Type                             Name           Plan       Info
 +   pulumi:pulumi:Stack              test2-dev3     create
 +   ├─ azure:core:ResourceGroup      resourceGroup  create
 +   ├─ azure:keyvault:KeyVault       keyvault       create
 +   ├─ azure:appservice:Plan         plan           create
 +   ├─ azure:storage:Account         storage        create
 +   ├─ azure:appservice:FunctionApp  function       create
     └─ azure:keyvault:AccessPolicy   app                       2 errors

Diagnostics:
  azure:keyvault:AccessPolicy (app):
    error: azure:keyvault/accessPolicy:AccessPolicy resource 'app' has a problem: "tenant_id": required field is not set
    error: azure:keyvault/accessPolicy:AccessPolicy resource 'app' has a problem: "object_id": required field is not set

error: an error occurred while advancing the preview
```

Why does pulumi does not accept the `tenant_id` and `object_id` the `pulumi.Output` as field?

**Comment by mikhailshilkov** [comment]
Bumped into the same issue today while trying to link KeyVault to an App Service.

A dumb workaround is to create an App Service / Function App first (run `pulumi up` without a vault defined) and then add a key vault and run the program again. It succeeded for me @StefanSchoof 

So, it seems that the terraform provider has issues when `tenantId`/`objectId` are set to the output of not-yet-existing resource. @jen20 @luke any hints of what to look for? Anything wrong [here](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_key_vault_access_policy.go)?

Side question - could we take `tenantId` from subscription properties automatically without requiring a developer to fill it?

**Comment by StefanSchoof** [comment]
Thank for the workaround. For me this was the bump, which let me stay at my terraform files (where this is working).

**Comment by mikhailshilkov** [comment]
Two more examples of the same issue:

``` ts
new azure.sql.ActiveDirectoryAdministrator("admins", {
    resourceGroupName: resourceGroup.name,
    tenantId: clientConfig.apply(c => c.tenantId),
    objectId: app.identity.principalId,
    login: "adadmin",
    serverName: sqlServer.name,
});

new azure.role.Assignment("readmyblob", {
    principalId: app.identity.principalId,
    scope: storageAccount.id,
    roleDefinitionName: "Storage Blob Data Reader",
});
```

For both, preview fails with `"object_id": required field is not set` or `"principal_id": required field is not set`. `pulumi up --skip-preview` works just fine.

I would prioritize this issue as it seems to jeopardize a lot of scenarios for no good reason.

**Comment by lukehoban** [comment]
I believe this is caused by https://github.com/pulumi/pulumi/issues/2433.  This causes `undefined` instead of `Unknown` to get passed through, which then gets erased at the marshalling boundary.

From verbose logs notice that `keyVaultId` is present in the values marshalled to the provider, but `objectId` and `tenantId` are not.

```
I0527 11:05:21.713891   48159 rpc.go:69] Marshaling property for RPC[Provider[azure, 0xc0012ee900].Check(urn:pulumi:dev::azure192::azure:keyvault/accessPolicy:AccessPolicy::app).news]: keyPermissions={[]}
I0527 11:05:21.714003   48159 rpc.go:69] Marshaling property for RPC[Provider[azure, 0xc0012ee900].Check(urn:pulumi:dev::azure192::azure:keyvault/accessPolicy:AccessPolicy::app).news]: keyVaultId=output<string>{}
I0527 11:05:21.714026   48159 rpc.go:69] Marshaling property for RPC[Provider[azure, 0xc0012ee900].Check(urn:pulumi:dev::azure192::azure:keyvault/accessPolicy:AccessPolicy::app).news]: secretPermissions={[{get}]}
I0527 11:05:21.714864   48159 rpc.go:215] Unmarshaling property for RPC[Provider[azure, 0xc0012ee900].Check(urn:pulumi:dev::azure192::azure:keyvault/accessPolicy:AccessPolicy::app).inputs]: __defaults={[]}
I0527 11:05:21.714885   48159 rpc.go:215] Unmarshaling property for RPC[Provider[azure, 0xc0012ee900].Check(urn:pulumi:dev::azure192::azure:keyvault/accessPolicy:AccessPolicy::app).inputs]: keyPermissions={[]}
I0527 11:05:21.714894   48159 rpc.go:215] Unmarshaling property for RPC[Provider[azure, 0xc0012ee900].Check(urn:pulumi:dev::azure192::azure:keyvault/accessPolicy:AccessPolicy::app).inputs]: keyVaultId=output<string>{}
I0527 11:05:21.714903   48159 rpc.go:215] Unmarshaling property for RPC[Provider[azure, 0xc0012ee900].Check(urn:pulumi:dev::azure192::azure:keyvault/accessPolicy:AccessPolicy::app).inputs]: secretPermissions={[{get}]}
I0527 11:05:21.714915   48159 provider_plugin.go:302] Provider[azure, 0xc0012ee900].Check(urn:pulumi:dev::azure192::azure:keyvault/accessPolicy:AccessPolicy::app) success: inputs=#4 failures=#2
```

**Comment by lukehoban** [comment]
BTW - two available workaround until this is fixed:

1. Do `pulumi up --skip-preview` on the first deployment.  This issue only affects when a preview is done before any updates have been done, so will not occur on future `pulumi up`s.

2. Add a default value in the `.apply` - like `functionApp.identity.apply(identity => identity.principalId || "11111111-1111-1111-1111-111111111111")` (in this case, ensuring the default passes the UUID length check).  This default shouldn't be needed (that's the bug here), but will only be seen on the first ever preview before any deployment has completed.

**Comment by lukehoban** [comment]
I'm going to close this as a dupe of https://github.com/pulumi/pulumi/issues/2433.

**Comment by mikhailshilkov** [comment]
@lukehoban @pat Is this supposed to work now? I'm still getting errors in preview if I remove the ` || "11111111-1111-1111-1111-111111111111"` workaround [here](https://github.com/pulumi/examples/blob/master/azure-ts-msi-keyvault-rbac/index.ts#L133).

**Comment by pat** [comment]
@mikhailshilkov I think you meant to tag @pgavlin rather than myself :)

**Comment by mikhailshilkov** [comment]
@pat 🤦‍♂ I'm sorry for disturbing!

**Comment by pgavlin** [comment]
I believe this will be fixed with the next release: the code that should address this did not make it into 1.2.0.

**Comment by mikhailshilkov** [comment]
@pgavlin Actually, it's the opposite. I was testing with the latest master and the preview was failing. However, `1.2.0` does work.

It turns out that #3245 caused regression and this issue is back now. I verify that by testing commit-by-commit and finding the first one that stops working.

**Comment by pgavlin** [comment]
> It turns out that #3245 caused regression and this issue is back now. I verify that by testing commit-by-commit and finding the first one that stops working.

Got it. I think this one is essentially by design, then: because the input has a value that is known, we do not know when using the current approach that it may change during the update. In this case, the update would populate the missing fields. This would be solvable using the "provider dry-run" approach outlined in https://github.com/pulumi/pulumi/issues/3190.

For now, I am going to close this as by-design with the documented workarounds.

**Comment by ilmax** [comment]
@pgavlin this is happening with the C# SDK as well and the `identity.principalId || "11111111-1111-1111-1111-111111111111"` doesn't seems to work.

Sample code:
```csharp
var appService = new AppService(name, appServiceArgs);
new AccessPolicy($"read-{name}", new AccessPolicyArgs
{
	KeyVaultId = GetOutputValue("Azure:KeyVault:Id"),
	ObjectId = appService.Identity.Apply(identity => identity.PrincipalId),
	TenantId = tenantId,
	SecretPermissions = new InputList<string>
	{
		"get",
		"list"
	}
});
```
Is there a work around also for the C# SDK other than `pulumi up --skip-preview`?
Moreover do you want me to open a new issue?

**Comment by lukehoban** [comment]
Reopening - we’ve seen a lot of folks continue to hit this - and although it is arguably “by design” currently:
1. That design leads to violating our type system
2. It’s very unintuitive and hard to even figure out why it’s happening or what to do

I think we will need to continue to think about improving the experience here.

**Comment by lukehoban** [comment]
Note that on top of impacting the initial preview (as noted in https://github.com/pulumi/pulumi-azure/issues/192#issuecomment-496279536), this seems to also currently trigger any time a resource is being updated, which has an output that is a filled in version of something provided as an input. This broadens the impact of this issue meaningfully

**Comment by mikhailshilkov** [comment]
I tried it with the latest version and, FWIW, the workaround still works both for the initial preview and subsequent updates, both for TypeScript and C#.

@ilmax This C# snippet resolves the problem for me:

```cs
var principalId = appService.Identity.Apply(id => id.PrincipalId ?? "11111111-1111-1111-1111-111111111111");
```

I agree the workaround isn't great and is hard to discover.

**Comment by ilmax** [comment]
After trying it again, I can confirm it work with the ?? "something" workaround, my bad.

**Comment by DerAlbertCom** [comment]
I also run into that problem, this is not that intuitiv.

**Comment by DerAlbertCom** [comment]
Also Updating with this workaround leads to a replace in preview, which is finally not done, but is confusing.

![image](https://user-images.githubusercontent.com/136992/75354460-4812ce80-58ad-11ea-9020-12539ae33e72.png)

**Comment by robertwe** [comment]
Same issue here (Pulumi v2.5 azure provider v3.10). I can use trick `|| "11111111-1111-1111-1111-111111111111"` but as @DerAlbertCom mentioned I got diff on preview all the time.

**Comment by elsesiy** [comment]
@lukehoban @clstokes This is becoming a real issue for us. We can't tell ahead of a `pulumi up` what resources are going to be changed because the `pulumi preview` is misleading (diff shows a whole lot of scary changes that are just calculated due to the placeholder valule). I'm very hesitant to do any applies against prod right now because of this.

This is what we have to prevent panics in Go:
```
	k8sClusterIdentity := k8s.Cluster.Identity.ApplyT(func(i interface{}) (string, error) {
		id := i.(*containerservice.KubernetesClusterIdentity).PrincipalId
		if id == nil {
			return "11111111-1111-1111-1111-111111111111", nil
		}

		return *id, nil
	}).(pulumi.StringOutput)

	k8sKubeletIdentity := k8s.Cluster.KubeletIdentities.ApplyT(func(kIds []containerservice.KubernetesClusterKubeletIdentity) (string, error) {
		if len(kIds) == 0 {
			return "11111111-1111-1111-1111-111111111111", nil
		}
		return *kIds[0].ObjectId, nil
	}).(pulumi.StringOutput)
```

With this in place, the slightest change to any dependent resource shows up as `delete-replace` which shouldn't be the case.

**Comment by MisinformedDNA** [comment]
Bump.

**Comment by JasonWhall** [comment]
+1 Also seeing the same behaviour with AKS clusters created with Managed identities. It's a pre-requisite for the AKS cluster identity to have Network Contributor on the Resource Group it is deployed to when using Azure CNI.

```
var aks = new KubernetesCluster(name, new KubernetesClusterArgs
{
// Other Stuff goes here to create aks cluster
    Identity = new KubernetesClusterIdentityArgs
    {
        Type = "SystemAssigned"
    },
}

_ = new Assignment("aks-subnet-role", new AssignmentArgs
{
    PrincipalId = aks.Identity.Apply(identity => identity?.PrincipalId ?? "11111111-1111-1111-1111-111111111111"),
    RoleDefinitionName = "Network Contributor",
    Scope = myResourceGroupId,
});
```

I get some odd behaviour where it works sometimes and others it will refer to the `11111111-1111-1111-1111-111111111111` in the preview

**Comment by lukehoban** [comment]
The work on https://github.com/pulumi/pulumi/issues/4992 (in particular https://github.com/pulumi/pulumi/pull/5443) is likely to improve things here.  @pgavlin can you review and update on what the behaviour will be after those changes land?

**Comment by pgavlin** [comment]
This is fixed as of https://github.com/pulumi/pulumi-azure/pull/741.

**Comment by scp-mb** [comment]
As requested by @mikhailshilkov over at https://github.com/pulumi/pulumi-azure-nextgen/issues/115 this seems to still be an issue, here is a basic reproduction under Pulumi 2.13.2 and Pulumi.Azure v3.30.0

```
        var resourceGroup = new ResourceGroup("TestResourceGroup",
            new ResourceGroupArgs
            {
                Location = "UKSouth"
            });

        var appServicePlan = new Pulumi.Azure.AppService.Plan("TestAppServicePlan", new PlanArgs
        {
            ResourceGroupName = resourceGroup.GetResourceName(),
            Location = "UKSouth",
            Sku = new PlanSkuArgs
            {
                Tier = "Standard",
                Capacity = 1,
                Size = "S1"
            },
            Kind = "app"
        });

        var appService = new AppService("TestAppService", new AppServiceArgs
        {
            ResourceGroupName = resourceGroup.GetResourceName(),
            AppServicePlanId = appServicePlan.Id,
            Location = "UKSouth",
            Identity = new Pulumi.Azure.AppService.Inputs.AppServiceIdentityArgs
            {
                Type = "SystemAssigned"
            }
        });

        new Pulumi.Azure.Authorization.Assignment($"{resourceGroup.GetResourceName()}-{appService.GetResourceName()}-permissions",
        new Pulumi.Azure.Authorization.AssignmentArgs
        {
            PrincipalId = appService.Identity.Apply(x => x.PrincipalId),
            Scope = resourceGroup.Id,
            RoleDefinitionName = "Contributor"
        });
```

Which leads to the following output with `pulumi preview`

```
     Type                               Name                                          Plan       Info
     pulumi:pulumi:Stack                Redacted-dev
 +   ├─ azure:core:ResourceGroup        TestResourceGroup                             create
 +   ├─ azure:appservice:Plan           TestAppServicePlan                            create
 +   ├─ azure:appservice:AppService     TestAppService                                create
     └─ azure:authorization:Assignment  TestResourceGroup-TestAppService-permissions             1 error

Diagnostics:
  azure:authorization:Assignment (TestResourceGroup-TestAppService-permissions):
    error: azure:authorization/assignment:Assignment resource 'TestResourceGroup-TestAppService-permissions' has a problem: Missing required property 'principalId'
```

**Comment by mikhailshilkov** [comment]
@pgavlin this sounds like the same scenario, any idea what is still missing?

**Comment by elsesiy** [comment]
@pgavlin We have the same issue. The provider-side preview only helps if the resources exist and you run a `preview`. For a new deployment we still panic if we don't define the placeholders mentioned above

**Comment by leezen** [comment]
As an update on this issue:
- We closed this issue thinking https://github.com/pulumi/pulumi/issues/4992 addressed this issue. However, it only addresses the case for updates where the resource already exists (as pointed out above).
- The previously documented workaround (to use `apply(s => s || "default")`) should continue to work in the create case. In the case of updates, pulumi/pulumi#4992 should address the spurious diffs previously seen. If you're still seeing spurious diffs on preview, please post in this issue.
- We're investigating ways to improve the behavior for creates such that we can flow unknown values through.

**Comment by leezen** [comment]
Closing this now that the version of the bridge in this provider includes https://github.com/pulumi/pulumi-terraform-bridge/pull/308
